### ISSUE TITLE
Key mapping does not work

### ISSUE THREAD

**Issue by huayue369** [anschnapp/move-less#4] opened 2019-04-14 22:41 UTC
Plug-in command manual input can work, but the key mapping does not work, I used neovim. Previously the mapping worked, but now only manual output works.
My English is not good! I am sorry, but I like this plugin very much.
![图片](https://user-images.githubusercontent.com/32536764/56100261-16b93a80-5f49-11e9-860c-e71c3ab60035.png)
![图片](https://user-images.githubusercontent.com/32536764/56100263-2769b080-5f49-11e9-9248-45e04facbf69.png)
This is the result given by echo maparg('<leader>z', 'n') and the feedback seems to be ok
![图片](https://user-images.githubusercontent.com/32536764/56100283-5e3fc680-5f49-11e9-9c4e-219d567e7051.png)

**Comment by anschnapp** [comment] 2019-04-24 19:01
I have tried to reproduce the issue but it worked on my machine. (tried on vim and nvim v0.3.4)

But why are you testing `echo maparg('z','n') shouldn't there be your leader key before the z? Maybe you just have another mapping on the same sequence...

I also guess a mapping of `nnoremap` would be a better fit, because mapping (in this way) would only work if you are in the normal mode.

If it's still not working, could you please check if you use the newest version and maybe try if it's work for you in a older version?

**Comment by anschnapp** [comment] 2020-04-19 08:57
OK, I guess I waited long enough for new information of this not reproducible bug.
So i close it for now, if anyone has new information on this, please let me now and i will reopen it.

**Closed as completed** 2020-04-19 08:58 UTC
